/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as PrimitivesRouteImport } from './routes/primitives'
import { Route as ComponentsSurfaceRouteImport } from './routes/components.$surface'
import { Route as DevFixturesRouteImport } from './routes/dev.fixtures'
import { Route as DevHooksRouteImport } from './routes/dev.hooks'
import { Route as DirectionsIndexRouteImport } from './routes/directions.index'
import { Route as DirectionsDirectionRouteImport } from './routes/directions.$direction'
import { Route as PagesSurfaceRouteImport } from './routes/pages.$surface'
import { Route as PreviewKindSurfaceVariantRouteImport } from './routes/preview.$kind.$surface.$variant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimitivesRoute = PrimitivesRouteImport.update({
  id: '/primitives',
  path: '/primitives',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSurfaceRoute = ComponentsSurfaceRouteImport.update({
  id: '/components/$surface',
  path: '/components/$surface',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFixturesRoute = DevFixturesRouteImport.update({
  id: '/dev/fixtures',
  path: '/dev/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHooksRoute = DevHooksRouteImport.update({
  id: '/dev/hooks',
  path: '/dev/hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsIndexRoute = DirectionsIndexRouteImport.update({
  id: '/directions/',
  path: '/directions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectionsDirectionRoute = DirectionsDirectionRouteImport.update({
  id: '/directions/$direction',
  path: '/directions/$direction',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSurfaceRoute = PagesSurfaceRouteImport.update({
  id: '/pages/$surface',
  path: '/pages/$surface',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewKindSurfaceVariantRoute =
  PreviewKindSurfaceVariantRouteImport.update({
    id: '/preview/$kind/$surface/$variant',
    path: '/preview/$kind/$surface/$variant',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/primitives': typeof PrimitivesRoute
  '/components/$surface': typeof ComponentsSurfaceRoute
  '/dev/fixtures': typeof DevFixturesRoute
  '/dev/hooks': typeof DevHooksRoute
  '/directions/$direction': typeof DirectionsDirectionRoute
  '/pages/$surface': typeof PagesSurfaceRoute
  '/directions/': typeof DirectionsIndexRoute
  '/preview/$kind/$surface/$variant': typeof PreviewKindSurfaceVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/primitives': typeof PrimitivesRoute
  '/components/$surface': typeof ComponentsSurfaceRoute
  '/dev/fixtures': typeof DevFixturesRoute
  '/dev/hooks': typeof DevHooksRoute
  '/directions/$direction': typeof DirectionsDirectionRoute
  '/pages/$surface': typeof PagesSurfaceRoute
  '/directions': typeof DirectionsIndexRoute
  '/preview/$kind/$surface/$variant': typeof PreviewKindSurfaceVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feedback': typeof FeedbackRoute
  '/primitives': typeof PrimitivesRoute
  '/components/$surface': typeof ComponentsSurfaceRoute
  '/dev/fixtures': typeof DevFixturesRoute
  '/dev/hooks': typeof DevHooksRoute
  '/directions/$direction': typeof DirectionsDirectionRoute
  '/pages/$surface': typeof PagesSurfaceRoute
  '/directions/': typeof DirectionsIndexRoute
  '/preview/$kind/$surface/$variant': typeof PreviewKindSurfaceVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feedback'
    | '/primitives'
    | '/components/$surface'
    | '/dev/fixtures'
    | '/dev/hooks'
    | '/directions/$direction'
    | '/pages/$surface'
    | '/directions/'
    | '/preview/$kind/$surface/$variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feedback'
    | '/primitives'
    | '/components/$surface'
    | '/dev/fixtures'
    | '/dev/hooks'
    | '/directions/$direction'
    | '/pages/$surface'
    | '/directions'
    | '/preview/$kind/$surface/$variant'
  id:
    | '__root__'
    | '/'
    | '/feedback'
    | '/primitives'
    | '/components/$surface'
    | '/dev/fixtures'
    | '/dev/hooks'
    | '/directions/$direction'
    | '/pages/$surface'
    | '/directions/'
    | '/preview/$kind/$surface/$variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedbackRoute: typeof FeedbackRoute
  PrimitivesRoute: typeof PrimitivesRoute
  ComponentsSurfaceRoute: typeof ComponentsSurfaceRoute
  DevFixturesRoute: typeof DevFixturesRoute
  DevHooksRoute: typeof DevHooksRoute
  DirectionsDirectionRoute: typeof DirectionsDirectionRoute
  PagesSurfaceRoute: typeof PagesSurfaceRoute
  DirectionsIndexRoute: typeof DirectionsIndexRoute
  PreviewKindSurfaceVariantRoute: typeof PreviewKindSurfaceVariantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primitives': {
      id: '/primitives'
      path: '/primitives'
      fullPath: '/primitives'
      preLoaderRoute: typeof PrimitivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$surface': {
      id: '/components/$surface'
      path: '/components/$surface'
      fullPath: '/components/$surface'
      preLoaderRoute: typeof ComponentsSurfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/fixtures': {
      id: '/dev/fixtures'
      path: '/dev/fixtures'
      fullPath: '/dev/fixtures'
      preLoaderRoute: typeof DevFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/hooks': {
      id: '/dev/hooks'
      path: '/dev/hooks'
      fullPath: '/dev/hooks'
      preLoaderRoute: typeof DevHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions/': {
      id: '/directions/'
      path: '/directions'
      fullPath: '/directions/'
      preLoaderRoute: typeof DirectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directions/$direction': {
      id: '/directions/$direction'
      path: '/directions/$direction'
      fullPath: '/directions/$direction'
      preLoaderRoute: typeof DirectionsDirectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$surface': {
      id: '/pages/$surface'
      path: '/pages/$surface'
      fullPath: '/pages/$surface'
      preLoaderRoute: typeof PagesSurfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$kind/$surface/$variant': {
      id: '/preview/$kind/$surface/$variant'
      path: '/preview/$kind/$surface/$variant'
      fullPath: '/preview/$kind/$surface/$variant'
      preLoaderRoute: typeof PreviewKindSurfaceVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedbackRoute: FeedbackRoute,
  PrimitivesRoute: PrimitivesRoute,
  ComponentsSurfaceRoute: ComponentsSurfaceRoute,
  DevFixturesRoute: DevFixturesRoute,
  DevHooksRoute: DevHooksRoute,
  DirectionsDirectionRoute: DirectionsDirectionRoute,
  PagesSurfaceRoute: PagesSurfaceRoute,
  DirectionsIndexRoute: DirectionsIndexRoute,
  PreviewKindSurfaceVariantRoute: PreviewKindSurfaceVariantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
