/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppRunsRouteImport } from './routes/_app/_runs'
import { Route as AppStatusRouteImport } from './routes/_app/status'
import { Route as AppRunsIndexRouteImport } from './routes/_app/_runs/index'
import { Route as AppRunsHistoryRouteImport } from './routes/_app/_runs/history'
import { Route as AppPullsPullNumberRouteImport } from './routes/_app/pulls.$pullNumber'
import { Route as AppRunsRunIdRouteImport } from './routes/_app/runs.$runId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/_runs',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRunsRoute,
} as any)
const AppRunsHistoryRoute = AppRunsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRunsRoute,
} as any)
const AppPullsPullNumberRoute = AppPullsPullNumberRouteImport.update({
  id: '/pulls/$pullNumber',
  path: '/pulls/$pullNumber',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRunsIndexRoute
  '/status': typeof AppStatusRoute
  '/history': typeof AppRunsHistoryRoute
  '/pulls/$pullNumber': typeof AppPullsPullNumberRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRunsIndexRoute
  '/status': typeof AppStatusRoute
  '/history': typeof AppRunsHistoryRoute
  '/pulls/$pullNumber': typeof AppPullsPullNumberRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/_runs': typeof AppRunsRouteWithChildren
  '/_app/status': typeof AppStatusRoute
  '/_app/_runs/history': typeof AppRunsHistoryRoute
  '/_app/pulls/$pullNumber': typeof AppPullsPullNumberRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
  '/_app/_runs/': typeof AppRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/status' | '/history' | '/pulls/$pullNumber' | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/status' | '/history' | '/pulls/$pullNumber' | '/runs/$runId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_runs'
    | '/_app/status'
    | '/_app/_runs/history'
    | '/_app/pulls/$pullNumber'
    | '/_app/runs/$runId'
    | '/_app/_runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_runs': {
      id: '/_app/_runs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_runs/': {
      id: '/_app/_runs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRunsRoute
    }
    '/_app/_runs/history': {
      id: '/_app/_runs/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppRunsHistoryRouteImport
      parentRoute: typeof AppRunsRoute
    }
    '/_app/pulls/$pullNumber': {
      id: '/_app/pulls/$pullNumber'
      path: '/pulls/$pullNumber'
      fullPath: '/pulls/$pullNumber'
      preLoaderRoute: typeof AppPullsPullNumberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRunsRouteChildren {
  AppRunsHistoryRoute: typeof AppRunsHistoryRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
}

const AppRunsRouteChildren: AppRunsRouteChildren = {
  AppRunsHistoryRoute: AppRunsHistoryRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
}

const AppRunsRouteWithChildren =
  AppRunsRoute._addFileChildren(AppRunsRouteChildren)

interface AppRouteChildren {
  AppRunsRoute: typeof AppRunsRouteWithChildren
  AppStatusRoute: typeof AppStatusRoute
  AppPullsPullNumberRoute: typeof AppPullsPullNumberRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRunsRoute: AppRunsRouteWithChildren,
  AppStatusRoute: AppStatusRoute,
  AppPullsPullNumberRoute: AppPullsPullNumberRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
