/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppStatusRouteImport } from './routes/_app/status'
import { Route as AppPullsPullNumberRouteImport } from './routes/_app/pulls.$pullNumber'
import { Route as AppRunsRunIdRouteImport } from './routes/_app/runs.$runId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any)
const AppPullsPullNumberRoute = AppPullsPullNumberRouteImport.update({
  id: '/pulls/$pullNumber',
  path: '/pulls/$pullNumber',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/history': typeof AppHistoryRoute
  '/status': typeof AppStatusRoute
  '/pulls/$pullNumber': typeof AppPullsPullNumberRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/history': typeof AppHistoryRoute
  '/status': typeof AppStatusRoute
  '/': typeof AppIndexRoute
  '/pulls/$pullNumber': typeof AppPullsPullNumberRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/status': typeof AppStatusRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pulls/$pullNumber': typeof AppPullsPullNumberRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/history' | '/status' | '/pulls/$pullNumber' | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/history' | '/status' | '/' | '/pulls/$pullNumber' | '/runs/$runId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/history'
    | '/_app/status'
    | '/_app/'
    | '/_app/pulls/$pullNumber'
    | '/_app/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pulls/$pullNumber': {
      id: '/_app/pulls/$pullNumber'
      path: '/pulls/$pullNumber'
      fullPath: '/pulls/$pullNumber'
      preLoaderRoute: typeof AppPullsPullNumberRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppStatusRoute: typeof AppStatusRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPullsPullNumberRoute: typeof AppPullsPullNumberRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppStatusRoute: AppStatusRoute,
  AppIndexRoute: AppIndexRoute,
  AppPullsPullNumberRoute: AppPullsPullNumberRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
